services:
  app:
    build: .
    container_name: python-todo-app
    ports:
      # Using 5001 to avoid the 'address in use' error on your Mac
      - "5001:5000"
    environment:
      # --- THIS IS THE CORRECTED LINE ---
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tododb
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    container_name: todo-db
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: